env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - XCPROJ="-project Harvest.xcodeproj -scheme Harvest-Package"

osx_image: xcode11

branches:
  only:
    - master
    - travis

matrix:
  include:
    - os: osx
      language: objective-c
      script:
        - set -o pipefail
        - make xcodeproj
        - make test ARG="-destination 'platform=OS X' $XCPROJ"
      env:
        - JOB=xcodebuild-macOS

    - os: osx
      language: objective-c
      script:
        - set -o pipefail
        - make xcodeproj
        - make test ARG="-destination 'platform=iOS Simulator,name=iPhone 11' $XCPROJ"
      env:
        - JOB=xcodebuild-iOS

    - os: osx
      language: objective-c
      script:
        - set -o pipefail
        - make xcodeproj
        - make test ARG="-destination 'platform=tvOS Simulator,name=Apple TV 4K' $XCPROJ"
      env:
        - JOB=xcodebuild-tvOS

    - os: osx
      language: objective-c
      script:
        - set -o pipefail
        - make xcodeproj
        - make build ARG="-destination 'platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm' $XCPROJ"
      env:
        - JOB=xcodebuild-watchOS

    - os: osx
      language: generic
      script:
        - swift --version
        - swift build
        #- swift test # Comment-Out: Combine is not supported
      env:
        - JOB=swiftpm-mac
