# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://github.com/actions/virtual-environments/blob/master/images/macos
name: CI

on:
  push:
    branches:
      - master
      - ci/**
  pull_request:

jobs:
  xcodebuild-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.3.app'
    - name: Make xcodeproj
      run: make xcodeproj
    - name: Run tests
      run: make test ARG="-destination 'platform=OS X' $XCPROJ"

  xcodebuild-iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.3.app'
    - name: Make xcodeproj
      run: make xcodeproj
    - name: Run tests
      run: make test ARG="-destination 'platform=iOS Simulator,name=iPhone 12 Pro' $XCPROJ"

  xcodebuild-tvOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.3.app'
    - name: Make xcodeproj
      run: make xcodeproj
    - name: Run tests
      run: make test ARG="-destination 'platform=tvOS Simulator,name=Apple TV 4K' $XCPROJ"

  xcodebuild-watchOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.3.app'
    - name: Make xcodeproj
      run: make xcodeproj
    - name: Build watchOS (no tests)
      run: make build ARG="-destination 'platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm' $XCPROJ"

  swiftpm-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.3.app'
    - name: swift build
      run: swift build
    # Comment-Out: Skip timing-fragile tests in CI
    # - name: Run tests
    #   run: HARVEST_SPM_TEST=1 swift test

env:
  XCPROJ: -project Harvest.xcodeproj -scheme Harvest-Package
